image: node:latest

stages:
  - build
  - deploy

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

build-yarn:
  stage: build

  cache:
    key: ${CI_COMMIT_REF_SLUG}-yarn-berry
    paths:
      - node_modules/
      - .yarn/cache
  artifacts:
    expire_in: 1 week
    paths:
      - dist
  script:
    - yarn
    - yarn test
    - yarn build
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

publish-yarn:
  stage: deploy
  needs:
    - build-yarn
  script:
    - yarn
    - echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .yarnrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .yarnrc
    - yarn npm publish
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
