name: Build & Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-yarn:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .yarn/cache
          key: ${{ runner.os }}-yarn-berry-${{ github.ref_name }}

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn test

      - name: Build project
        run: yarn build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
          retention-days: 7

  publish-yarn:
    name: Publish
    runs-on: ubuntu-latest
    needs: build-yarn
    if: github.ref == 'refs/heads/main'
    container:
      image: node:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore Yarn cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .yarn/cache
          key: ${{ runner.os }}-yarn-berry-${{ github.ref_name }}

      - name: Install dependencies
        run: yarn

      - name: Setup npm authentication
        run: |
          echo "@k-kondratowicz/form-validation:registry=https://npm.pkg.github.com" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      - name: Publish package
        run: yarn publish
